### ISSUE TITLE
DB - ScottheRole create error when creating a page under project

### ISSUE THREAD

**Issue by Lothandar** [QAC-Portal/QA-Portal#59]
When creating a page under a project if you select the associated role "ScottheRole": 
![image](https://user-images.githubusercontent.com/32268363/70039820-6faa1180-15b2-11ea-9a95-0d7b54546dc9.png)

and then press the update button it will return an error: 
![image](https://user-images.githubusercontent.com/32268363/70039899-83ee0e80-15b2-11ea-8f04-c64712d7163c.png)

and return an error 400 in the console:
![image](https://user-images.githubusercontent.com/32268363/70039954-99fbcf00-15b2-11ea-896b-5cb9121af7f6.png)

**Comment by ianowenQA** [comment]
Fixed by @renJoseph
