### ISSUE TITLE
badly aligned radio buttons on smaller windows

### ISSUE THREAD

**Issue by EkowTheGreat** [QAC-Portal/QA-Portal#71]
Radio buttons on self reflection page and trainee course evaluation do not stay within bounds of the div on smaller windows.
![radiobuttons](https://user-images.githubusercontent.com/56401507/70130105-e1985e80-1677-11ea-8f91-4ec7c0b76912.png)

**Comment by ianowenQA** [comment]
Fixed as part of #73
